spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialize: true
    initialization-mode: always
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  messages:
    basename: bundles/apiLanguageBundle

ssmu-api:
  openapi:
    dev-url: http://localhost:8080/ssmu-api
    prod-url: https://ssmu-api.com

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html # Ruta de acceso para la interfaz de Swagger-UI
  api-docs:
    enabled: true # Habilitar la generaci贸n de documentaci贸n OpenAPI
    path: /v3/api-docs # Ruta de acceso para los documentos OpenAPI
  show-actuator: true # Habilitar la visualizaci贸n de los endpoints de actuator
  version: 3.0.0 # Versi贸n de OpenAPI

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
